[pytest]
addopts = 
    --alluredir=allure-results
    -v
    --tb=short
    --strict-markers
    --color=yes
markers =
    smoke: Smoke tests
    ui: UI tests
    navigation: Navigation tests
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*